FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

# Installing rust
RUN apt-get update && apt-get install -y curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Installing python 3.10
RUN apt-get update && apt-get install -y python3.10 python3.10-distutils
RUN ln -s /usr/bin/python3.10 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip

# Install Python and pip
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

# Set the working directory in the container
WORKDIR /app

# Copy the contents of the root directory into the container
COPY ../../ /app/